[package]
name = "rustui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
diplomat = "0.8.0"
diplomat-runtime = "0.8.0"
fdp-definition = { path = "../../fdp-core/fdp-definition" }

[build-dependencies]
diplomat = "0.8.0"
