[package]
name = "fdp-mqtt-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full", "test-util"] }
mqtt-client = { path = "../../mqtt-client" }
fdp-common = { path = "../fdp-common" }
