[package]
name = "fdp-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
schemars = "0.8.16"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "visit"] }
quote = "1.0"
petgraph = "0.6.5"
